name: "0-Pipeline"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    paths:
      - 'my-static-website/**'
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  integration:
    uses: ./.github/workflows/1-integration.yml
    permissions:
      contents: read

  delivery:
    needs: [integration]
    uses: ./.github/workflows/2-delivery.yml
    permissions:
      contents: read
      packages: write
      id-token: write

  staging:
    needs: [delivery]
    uses: ./.github/workflows/3-deployment.yml
    with:
      environment: Staging
    permissions:
      packages: read
    secrets: inherit

  production:
    needs: [staging]
    uses: ./.github/workflows/3-deployment.yml
    with:
      environment: Production
    permissions:
      packages: read
    secrets: inherit